# Generated by Django 3.2.5 on 2021-07-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=254, verbose_name='Полное имя пользователя')),
                ('comment', models.TextField(blank=True, max_length=500, verbose_name='Коментарий')),
                ('created_add', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('rating', models.IntegerField(blank=True, verbose_name='Рейтинг')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d/', verbose_name='Фото')),
                ('name_product', models.CharField(max_length=254, verbose_name='Наименование товара')),
                ('description_product', models.TextField(max_length=500, verbose_name='Описание товара')),
            ],
        ),
    ]
